<%@ Page Title="" Language="C#" MasterPageFile="~/JetBoxHome.Master" AutoEventWireup="true" CodeBehind="home.aspx.cs" Inherits="JetBox.WebForm1" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <link type ="text/css" rel="stylesheet" href="home.css" />
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <p>
    Home</p>
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolder2" runat="server">
    <p>
    <a href="MovieList.aspx">Movies List</a></p>
</asp:Content>
<asp:Content ID="Content4" ContentPlaceHolderID="ContentPlaceHolder3" runat="server">
    <p>
    <a href="Login.aspx">Sign In</a></p>
</asp:Content>
<asp:Content ID="Content5" ContentPlaceHolderID="ContentPlaceHolder4" runat="server">
    <p>
    Search</p>
</asp:Content>
<asp:Content ID="Content6" ContentPlaceHolderID="ContentPlaceHolder6" runat="server">
    <p>
    Cart</p>
</asp:Content>
<asp:Content ID="Content7" ContentPlaceHolderID="MainContentArea" runat="server">
    <div>
    Popular Movies
<link rel="stylesheet" type="text/css" href="slide_window.css" />

<div id="wowslider-container1">
<div class="ws_images"><ul>
<li><img src="https://image.tmdb.org/t/p/w185/1n9D32o30XOHMdMWuIT4AaA5ruI.jpg" alt="Bratislava castle, Slovakia timeline right to left rotator tab" title="Bratislava castle, Slovakia" id="wows1_0"/></li>
<li><img src="https://image.tmdb.org/t/p/w185/5aGhaIHYuQbqlHWvWYqMCnj40y2.jpg" alt="Bratislava, Slovakia simple header banner free download for ie8" title="Bratislava, Slovakia" id="wows1_1"/></li>
<li><img src="https://image.tmdb.org/t/p/w185/kqjL17yufvn9OVLyXYpvtyrFfak.jpg" alt="Bridge image plugin supported by all browsers ajax django" title="Bridge" id="wows1_2"/></li>
<li><img src="https://image.tmdb.org/t/p/w185/nBNZadXqJSdt05SHLqgT0HuC5Gm.jpg" alt="Dvorakovo nabrezie, Bratislava 3d light box navigation for mobile" title="Dvorakovo nabrezie, Bratislava" id="wows1_3"/></li>
<li><img src="https://image.tmdb.org/t/p/w185/e5jbaEiWYHtstuHPHl3lGPoRs4c.jpg" alt="Main square, Bratislava change speed easing v1 what is code for making" title="Main square, Bratislava" id="wows1_4"/></li>
<li><img src="https://image.tmdb.org/t/p/w185/9gm3lL8JMTTmc3W4BmNMCuRLdL8.jpg" alt="Night view like albums photos image iu" title="Night view" id="wows1_5"/></li>
<li><img src="https://image.tmdb.org/t/p/w185/69Cz9VNQZy39fUE2g0Ggth6SBTM.jpg" alt="Tree in the park, Bratislava image file download smooth demo php" title="Tree in the park, Bratislava" id="wows1_6"/></li>
<li><img src="https://image.tmdb.org/t/p/w185/z2sJd1OvAGZLxgjBdSnQoLCfn3M.jpg" alt="In the twilight maker free for websites image with navigation buttons using" title="In the twilight" id="wows1_7"/></li>
</ul></div>
        <!-- Generated by WOWSlider.com v5.0 -->
<a href="#" class="ws_frame"></a>
</div>
<script type="text/javascript" src="slide_engine.js"></script>
<script type="text/javascript" src="http://wowslider.com/sliders/demo-3/engine1/script.js"></script>
        <!-- End WOWSlider.com BODY section -->
<br />
</div>
<div>
Coming Soon!
    <div id="wowslider-container1">
<div class="ws_images"><ul>
<li><img src="http://wowslider.com/sliders/demo-3/data1/images/bratislavacastle.jpg" alt="Bratislava castle, Slovakia timeline right to left rotator tab" title="Bratislava castle, Slovakia" id="wows1_0"/></li>
<li><img src="http://wowslider.com/sliders/demo-3/data1/images/bratislava.jpg" alt="Bratislava, Slovakia simple header banner free download for ie8" title="Bratislava, Slovakia" id="wows1_1"/></li>
<li><img src="http://wowslider.com/sliders/demo-3/data1/images/bridge.jpg" alt="Bridge image plugin supported by all browsers ajax django" title="Bridge" id="wows1_2"/></li>
<li><img src="http://wowslider.com/sliders/demo-3/data1/images/dvorakovonabrezie.jpg" alt="Dvorakovo nabrezie, Bratislava 3d light box navigation for mobile" title="Dvorakovo nabrezie, Bratislava" id="wows1_3"/></li>
<li><img src="http://wowslider.com/sliders/demo-3/data1/images/mainsquare.jpg" alt="Main square, Bratislava change speed easing v1 what is code for making" title="Main square, Bratislava" id="wows1_4"/></li>
<li><img src="http://wowslider.com/sliders/demo-3/data1/images/night.jpg" alt="Night view like albums photos image iu" title="Night view" id="wows1_5"/></li>
<li><img src="http://wowslider.com/sliders/demo-3/data1/images/tree.jpg" alt="Tree in the park, Bratislava image file download smooth demo php" title="Tree in the park, Bratislava" id="wows1_6"/></li>
<li><img src="http://wowslider.com/sliders/demo-3/data1/images/twilight.jpg" alt="In the twilight maker free for websites image with navigation buttons using" title="In the twilight" id="wows1_7"/></li>
</ul></div>
        <!-- Generated by WOWSlider.com v5.0 -->
<a href="#" class="ws_frame"></a>
</div>
</div>
<footer>Footer</footer>
</asp:Content>
